### ISSUE TITLE
No Support for PHP5

### ISSUE THREAD

**Issue by sagarguhe** [spatie/pdf-to-text#1]
I noticed that it doesn't have any support for the current PHP version i.e. 5.4 or 5.5 which is provided by most of the shared hosting provider as a latest version. PHP7 is still missing from most of the shared hosting provider. Even many PHP Frameworks still don't support PHP7 if we leave a few.

PHP5 support should be provided.

Regards,
Sagar Guhe

**Comment by freekmurze** [comment]
Here's our reasoning for requiring PHP 7: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/
