### ISSUE TITLE
It shows me error of path?

### ISSUE THREAD

**Issue by ammydon** [spatie/pdf-to-text#14]
I am getting below error:
The command \"\"/usr/bin/pdftotext\" C:\\Users\\pay_slip.pdf -\" failed.\n\nExit Code: -1073741515(Unknown error)\n\nWorking directory: C:\\xampp\\htdocs\\caps_admin\\public\n\nOutput:\n================\n\n\nError Output:\n================\n"

my code in controller:

$text = (new Pdf())
		    ->setPdf('C:\Users\pay_slip.pdf')
		    ->text();
		    echo Pdf::getText('C:\Users\pay_slip.pdf');die();

**Comment by freekmurze** [comment]
Probably this is related to your specific setup and not this package.
