### ISSUE TITLE
Make process running configurable (timeout)

### ISSUE THREAD

**Issue by robsontenorio** [spatie/pdf-to-text#17]
Just noticed Symfony's Process class is used in this package. 

https://github.com/spatie/pdf-to-text/blob/184907c6723b956f8f9b584587bb0c0665b8f7b8/src/Pdf.php#L55

Some large PDF files get more than 60 seconds to be processed. 

Would be useful if we can set some custom settings on process running.

**Comment by nocodelab** [comment]
Same issue here.
@robsontenorio did you find any elegant way to fix it rather than edit the library itself?

**Comment by ErnestStaug** [comment]
Any update on this? This makes this package unusable with our app as most of our pdf's are big.

**Comment by freekmurze** [comment]
No, and we have no plans. If you want this fixed, you'll have to invest your time to create a fix.

**Comment by FlshBm** [comment]
`<?php

namespace Spatie\PdfToText;

use Spatie\PdfToText\Exceptions\CouldNotExtractText;
use Spatie\PdfToText\Exceptions\PdfNotFound;
use Symfony\Component\Process\Process;

class Pdf
{
    protected string $pdf;

    protected string $binPath;

    protected array $options = [];

    protected int $timeOut = 60;

    public function __construct(?string $binPath = null)
    {
        $this->binPath = $binPath ?? '/usr/bin/pdftotext';
    }

    public function setPdf(string $pdf): self
    {
        if (!is_readable($pdf)) {
            throw new PdfNotFound("Could not read `{$pdf}`");
        }

        $this->pdf = $pdf;

        return $this;
    }

    public function setTimeOut($timeOut) {
        $this->timeOut = $timeOut;
        return $this;
    }

    public function setOptions(array $options): self
    {
        $this->options = $this->parseOptions($options);

        return $this;
    }

    public function addOptions(array $options): self
    {
        $this->options = array_merge(
            $this->options,
            $this->parseOptions($options)
        );

        return $this;
    }

    protected function parseOptions(array $options): array
    {
        $mapper = function (string $content): array {
            $content = trim($content);
            if ('-' !== ($content[0] ?? '')) {
                $content = '-'.$content;
            }

            return explode(' ', $content, 2);
        };

        $reducer = function (array $carry, array $option): array {
            return array_merge($carry, $option);
        };

        return array_reduce(array_map($mapper, $options), $reducer, []);
    }

    public function text(): string
    {
        $process = new Process(array_merge([$this->binPath], $this->options, [$this->pdf, '-']));
        $process->setTimeout($this->timeOut);
        $process->run();
        if (!$process->isSuccessful()) {
            throw new CouldNotExtractText($process);
        }

        return trim($process->getOutput(), " \t\n\r\0\x0B\x0C");
    }

    public static function getText(string $pdf, ?string $binPath = null, array $options = []): string
    {
        return (new static($binPath))
            ->setOptions($options)
            ->setPdf($pdf)
            ->text()
        ;
    }
}
`
