### ISSUE TITLE
Successive calls to setOptions() overrides previously set options

### ISSUE THREAD

**Issue by garethellis36** [spatie/pdf-to-text#18]
In our container we are returning the  `Pdf ` object with default options:

```php
<?php
function ($container) {
    return (new \Spatie\PdfToText\Pdf($container['PdfToTextPath']))->setOptions(["-enc UTF-8"]);
}
?>
```

Then in code elsewhere we are adding other options specific to that use-case:

```php
<?php
$pdf->setOptions(["-f 2"]);
```

Doing this overrides the 'default' options set in the container factory function.

I am happy to work on a PR for this if you are happy for this functionality to be added (e.g. `Pdf::addOptions()`.

**Comment by freekmurze** [comment]
Handled by #19
