### ISSUE TITLE
Getting error Fatal error: Uncaught Spatie\PdfToText\Exceptions\CouldNotExtractText: The command "'/usr/bin/pdftotext' 'INVP0201_301345038.pdf' '-'" failed. 

### ISSUE THREAD

**Issue by startbitsolutions** [spatie/pdf-to-text#21]
Fatal error: Uncaught Spatie\PdfToText\Exceptions\CouldNotExtractText: The command "'/usr/bin/pdftotext' 'INVP0201_301345038.pdf' '-'" failed. Exit Code: 126(Invoked command cannot execute) Working directory: /var/www/html/reader/test Output: ================ Error Output: ================ sh: 1: exec: /usr/bin/pdftotext: Permission denied in /var/www/html/reader/test/vendor/spatie/pdf-to-text/src/Pdf.php:73 Stack trace: #0 /var/www/html/reader/test/vendor/spatie/pdf-to-text/src/Pdf.php(84): Spatie\PdfToText\Pdf->text() #1 /var/www/html/reader/test/index.php(10): Spatie\PdfToText\Pdf::getText('INVP0201_301345...') #2 {main} thrown in /var/www/html/reader/test/vendor/spatie/pdf-to-text/src/Pdf.php on line 73

I'm using PHP 7.2 v with Spatie\PdfToText\ latest version on server

**Comment by freekmurze** [comment]
This is most likely a permissions issue. Make sure your php process has the rights to call `pdftotext`.

**Comment by alaminfirdows** [comment]
Get the same error! Did anyone solve it?

**Comment by tusharkhan** [comment]
> Get the same error! Did anyone solve it?
Same error

**Comment by vecca26** [comment]
same issue anyone with a proper solution?

**Comment by alaminfirdows** [comment]
* For MAC, add the path of "pdftotext" library as follows
```php
use Spatie\PdfToText\Pdf;

$text = (new Pdf('/usr/local/bin/pdftotext'))
    ->setPdf('./test.pdf')
    ->text();

```
* For Linux/Ubuntu please leave
```php
use Spatie\PdfToText\Pdf;

$text = (new Pdf())
    ->setPdf('./test.pdf')
    ->text();

```
* For Windows, add the path of "pdftotext" library 
```php
use Spatie\PdfToText\Pdf;

$text = (new Pdf())
    ->setPdf('./test.pdf')
    ->text();

```
or 
```php
use Spatie\PdfToText\Pdf;

$text = (new Pdf('/usr/local/bin/pdftotext'))
    ->setPdf('./test.pdf')
    ->text();

```

* Install/Update Dependencies.
```bash
 composer update
```

**Comment by Expertweblancer** [comment]
`Spatie\PdfToText\Exceptions\CouldNotExtractText
The command ""/usr/bin/pdftotext" "F:\XAMPP7.4\htdocs\documentsearch\public/uploads/documents/1626025500TOPSPACE-NDA.pdf" -" failed. Exit Code: 1(General error) Working directory: F:\XAMPP7.4\htdocs\documentsearch\public Output: ================ Error Output: ================ The system cannot find the path specified.`

This is the error that I am getting...

**Comment by yustiandikma** [comment]
@Expertweblancer i got same problem like you, have you get the solution?

**Comment by alaminfirdows** [comment]
> @Expertweblancer i got same problem like you, have you get the solution?

Make sure the 'pdftotext' extension is installed and configured properly.

You can check the path by running `which pdftotext` command on ubuntu. If you are using windows then check this path `usr/local/bin/pdftotext`.

https://github.com/spatie/pdf-to-text/issues/21#issuecomment-647156173

**Comment by php32** [comment]
@yustiandikma run this command ` where is pdftotext` and then add following path.

\Spatie\PdfToText\Pdf::getText($path, 'C:\Program Files\Git\mingw64\bin\pdftotext.exe');

It's worked for me i hope it's work for you

**Comment by Suhail-Mansoori** [comment]
if ($request->hasFile('document')) {

            $binpath = 'C:/Program Files/Git/mingw64/bin/pdftotext';
            if (true) {
                $text = Pdf::getText($request->file('document'),$binpath);
            }else{
                $text = Pdf::getText($file);
            }
            
            return response()->json(['text' => $text]);
        } else {
            return response()->json(['message' => 'No file uploaded'], 400);
        }

**Comment by motosderua** [comment]
I've been trying to solve this for hours.
Spatie
 \ 
PdfToText
 \ 
Exceptions
 \ 
CouldNotExtractText
PHP 8.1.20
10.13.5
The command "'/usr/local/bin/pdftotext' '/tmp/phpsxAmO3' '-'" failed. Exit Code: 127(Command not found) Working directory: /var/www/public Output: ================ Error Output: ================ sh: 1: exec: /usr/local/bin/pdftotext: not found

**Comment by phanthanhluc24** [comment]
> @yustiandikma run this command ` where is pdftotext` and then add following path.
> 
> `\Spatie\PdfToText\Pdf::getText($path, 'C:\Program Files\Git\mingw64\bin\pdftotext.exe');`
> 
> It's worked for me i hope it's work for you

Thank you so much, it also work fro me
