### ISSUE TITLE
Different results in a Windows Local and Linux Prod 

### ISSUE THREAD

**Issue by CasonWebDev** [spatie/pdf-to-text#23]
hi, i'm trying to read the same file i read in a local development windows on my centOS vpn production but the results are diferent... anyone knows how resolve this?

![image](https://user-images.githubusercontent.com/6971584/61381680-cfad4f00-a881-11e9-9b91-52836bc07b16.png)
CENTOS PROD

![image](https://user-images.githubusercontent.com/6971584/61381726-df2c9800-a881-11e9-9801-11427ca8c7da.png)
WINDOWS LOCAL

**Comment by vdbelt** [comment]
This package uses [pdftotext](https://www.xpdfreader.com/pdftotext-man.html), so you may want to try the different options as listed in the manual to see if you get the desired results. 

Perhaps the Windows port has some different defaults.

Try the layout and/or eol option. 

The README includes [usage instructions](https://github.com/spatie/pdf-to-text#usage) on how to pass options to `pdftotext`.

**Comment by CasonWebDev** [comment]
Ok... i solved the issue, the pdftotext package i've installed is different, i've followed the readme, but the pdftotext in the poppler-utils is not the pdftotext from xpdf library, that's was the problem
thanks for help.

**Comment by roomoraaes** [comment]
@CasonWebDev I have the same issue, how do you solve it? I am using pdftotext.exe from XPDF on windows and using pdftotext to linux, but the result is different for them

**Comment by CasonWebDev** [comment]
@roomoraaes so... i'm not using the .exe file... i'm only using the .bin file from XPDF,  and i'm running the application in a Linux environment, in my development environment i'm using the ubuntu bash in my windows,  that way i can have the same result in production and in development.
