### ISSUE TITLE
#pdftotext.exe

### ISSUE THREAD

**Issue by tvnr690** [spatie/pdf-to-text#25]
pdftotext is a .exe file , so i want to know that is it run in server if yes where to put this pdftotext.exe command in cpannel filemanager

`$path = 'c:/Program Files/Git/mingw64/bin/pdftotext';
echo Pdf::getText('cosmic.pdf', $path);`

or is there any other alternative for this?

**Comment by mkq10** [comment]
@tvnr690 how did you fix this ? i need this on server as well
