### ISSUE TITLE
Only to get the main content

### ISSUE THREAD

**Issue by emresaracoglu** [spatie/pdf-to-text#26]
Hello

Is it possible to detect _Header_ and _Footer_ from the PDF file and delete them before transferring them to the article?
Only to get the main content.

Thank you for this repo.

**Comment by freekmurze** [comment]
Currently, this is not possible.

**Comment by emresaracoglu** [comment]
Do you think in future versions? :) 
cc @freekmurze

**Comment by caocanhlinh** [comment]
I am interested in this issue.
