### ISSUE TITLE
Uncaught Error: Class 'Pdf' not found in php

### ISSUE THREAD

**Issue by xslackx** [spatie/pdf-to-text#27]
Interactive shell

php > require __DIR__ . '/vendor/autoload.php';
php > use Spatie\PdfToText\Pdf;
php > echo Pdf::getText('auxiliar_de_enfermagem.pdf');
PHP Warning:  Uncaught Error: Class 'Pdf' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
php >

**Comment by freekmurze** [comment]
This problem seems not to be related to our package.
