### ISSUE TITLE
Classss !!!!

### ISSUE THREAD

**Issue by kPlusPlus** [spatie/pdf-to-text#28]
Fatal error: Uncaught Error: Class 'Pdf' not found in P:\miau\PDF\test.php:13

**Comment by brideo** [comment]
If you're using composer you need to include the autoloader.

`<?php
require __DIR__.'/vendor/autoload.php';

use Spatie\PdfToText\Pdf;

echo Pdf::getText('list.pdf'); //returns the text from the pdf`
