### ISSUE TITLE
Namespace Error Usage of This code

### ISSUE THREAD

**Issue by AidaAmini** [spatie/pdf-to-text#3]
Hi, 

I am trying to use this code and here is the function that I am using

<?php
namespace Spatie\PdfToText\Test;

use Spatie\PdfToText\Exceptions\CouldNotExtractText;
use Spatie\PdfToText\Exceptions\PdfNotFound;
use Spatie\PdfToText\Pdf;

function get_txt()
{
	echo "here";
    $text = (new Pdf('/usr/local/bin/pdftotext'))
        ->setPdf('book.pdf')
        ->text();
    echo text;
}
get_txt();

I am getting this error. 
herePHP Fatal error:  Uncaught Error: Class 'Spatie\PdfToText\Pdf' not found in /Users/aminialocal/Documents/project/pdftotext/t.php:18
Can you help me how to fix this problem?

**Comment by freekmurze** [comment]
That file name where PHP is looking in for the class seems off. 

Did you install the package with composer? If so, run `composer dump-autoload` and try again.

**Comment by AidaAmini** [comment]
I am still getting the same issue, Should I end up having a folder called Spatie in my working place?

**Comment by freekmurze** [comment]
Have you installed this package with `composer require spatie/pdf-to-text`?

**Comment by ayushpratap** [comment]
I am also facing the same issue.

I did install pdf-to-text using composer.

I also did composer dump-autoload but still the error remains.

**Comment by BlackScorp** [comment]
@AidaAmini @ayushpratap 

just a question, did you included the autoload.php from the vendor folder which were created upon composer require ..?

**Comment by freekmurze** [comment]
I can't recreate this problem. Can anybody provide steps on how to get this error on MacOS?

**Comment by BlackScorp** [comment]
@freekmurze there is no problem, in your Usage in Readme you dont say that you include vendor/autoload.php ;) (thats what i assume)

**Comment by freekmurze** [comment]
Reopen the issue if the suggestion of @BlackScorp did not fix your problem.

**Comment by 7Sandman** [comment]
I have the same problem.

**Comment by l0I** [comment]
In any circumstance don't experiment with package in route. Move code to controller.
