### ISSUE TITLE
get text of docx file

### ISSUE THREAD

**Issue by umairasif** [spatie/pdf-to-text#31]
I am unable to read the file with docx extension. Things are working fine with doc files. Following is the code through which I am getting the text 
$file_content = Pdf::getText($user_data['profile_path'], env('WORDTOTEXT_PATH'));
I have set WORDTOTEXT_PATH as enviroment variable. I am using the exe file of antiword
WORDTOTEXT_PATH='C:\Program Files\Git\mingw64\bin\antiword'

**Comment by freekmurze** [comment]
Docx is not supported

**Comment by umairasif** [comment]
@freekmurze what will be the proper way to handle this issue?
