### ISSUE TITLE
Could not read exception when reading from url

### ISSUE THREAD

**Issue by TheAngelM97** [spatie/pdf-to-text#32]
I installed and configured everything and managed to get text from a local file.
But when I try to get it from a public url it returns a 

> Could not read exception

Here's my code: (I am using mac)

Throws exception
`return Pdf::getText('{any public url to a pdf file}', '/usr/local/bin/pdftotext');`

Works fine
`return Pdf::getText('{local file}', '/usr/local/bin/pdftotext');`

**Comment by mkwsra** [comment]
I have the same issue

**Comment by nicholaszuccarelli** [comment]
Bump. Same issue too.

**Comment by arndvs** [comment]
Bump. Is there any way to ge tthe text from a url hosted PDF?
