### ISSUE TITLE
Versioning problem with 1.51 => 1.6.0 

### ISSUE THREAD

**Issue by christosku** [spatie/pdf-to-text#55]
Previous release (1.5.1) has an "1.51" tag, thus it appears higher than 1.6.0 on packagist and is preferred over 1.6.0 when doing composer require/update.

![image](https://user-images.githubusercontent.com/905336/179217175-afbbae3a-2655-425a-afc8-fd3765f22977.png)

**Comment by freekmurze** [comment]
I was unsure if deleting that tag would cause problems for people on that version, so I chose the safe solution of tagging a new version 1.52 🙂
